service: nj2jp

provider:
  name: aws
  runtime: nodejs4.3
  cfLogs: true
  stage: development
  region: ap-northeast-1

plugins:
  - serverless-webpack

custom: ${file(./config.json)}

function:
  graphql:
    handler: handler.graphql
    events:
      - http:
          path: graphql
          method: post
          integration: lambda
          memorySize: 256
          timeout: 10
          cors: true
          response: headers:
            Access-Control-Allow-Origin: "'*'"
