service: nj2jp

provider:
  name: aws
  runtime: nodejs6.10
  cfLogs: true
  stage: development
  region: ap-northeast-1

plugins:
  - serverless-webpack
  - serverless-plugin-graphiql

custom:
  graphiql:
    babelOptions:
      presets: [es2015, stage-0]

functions:
  graphql:
    handler: handler.graphql
    events:
      - http:
          path: graphql
          method: post
          integration: lambda
          memorySize: 256
          timeout: 10
          cors: true
          response:
            headers:
              Access-Control-Allow-Origin: "'*'"
